### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by artxty** [tyshkovskii/typed-async-storage#6]
There are a lot of mistakes and typos in [README.md](https://github.com/artxty/typed-async-storage/blob/master/README.md) you could fix. Thank you! :)

**Comment by harshalkaigaonkar** [comment]
Hey @artxty , I would like to fix the README.md file.

**Comment by sai-pothuri** [comment]
Hello @artxty 
I would like to fix any typos or grammatical errors

**Comment by psk907** [comment]
Hello @artxty ,
I have gone through your README file and I'd love to add a touch of grammatical correctness and formatting to it.
Shall I go ahead?

**Comment by sonylomo** [comment]
Hey @artxty ,
I think the README file can also be a bit more descriptive, aside from the grammatical errors. I can really help out.

**Comment by romasinha** [comment]
Hey @artxty , I went through the README file and I would love to enhance the content a bit and correct grammar, substitute proper words. Shall I?

**Comment by artxty** [comment]
everyone is welcome, waiting for your PR's

**Comment by cooltacocodes** [comment]
I'm gonna to add a error fix or two to give everyone a chance to contribute.
